// netlify/functions/tracks.js
// Returns the static catalog.json generated by the ingestion script
const fs = require('fs');
const path = require('path');

exports.handler = async (event, context) => {
  try {
    const catalogPath = path.resolve(__dirname, '../../backend/catalog.json');
    const data = fs.readFileSync(catalogPath, 'utf-8');
    return {
      statusCode: 200,
      headers: { "Content-Type": "application/json" },
      body: data,
    };
  } catch (err) {
    console.error('Error reading catalog:', err);
    return {
      statusCode: 500,
      body: JSON.stringify({ error: 'Failed to load catalog' }),
    };
  }
};
