import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import dns from 'dns'

// Force IPv4-first so Windows doesn't route through broken IPv6 paths
dns.setDefaultResultOrder('ipv4first')

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      // Inline service worker registration (replaces manual registration in main.jsx)
      injectRegister: 'inline',
      // Include all assets that need to be pre-cached
      includeAssets: ['favicon.svg', 'icons/*.png', 'offline.html'],
      manifest: {
        name: 'SoundAura — Free Music for Everyone',
        short_name: 'SoundAura',
        description: 'Free ad-free music streaming in all languages. Tamil, Hindi, English, Telugu, Malayalam songs. Offline playback, ringtone cutter, powerful player. No login required.',
        start_url: '/',
        scope: '/',
        display: 'standalone',
        orientation: 'any',
        theme_color: '#00c9d4',
        background_color: '#070b14',
        categories: ['music', 'entertainment'],
        lang: 'en',
        dir: 'ltr',
        prefer_related_applications: false,
        icons: [
          { src: '/icons/icon-72.png',            sizes: '72x72',   type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-96.png',            sizes: '96x96',   type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-128.png',           sizes: '128x128', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-144.png',           sizes: '144x144', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-152.png',           sizes: '152x152', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-192.png',           sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-384.png',           sizes: '384x384', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-512.png',           sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: '/icons/icon-maskable-192.png',  sizes: '192x192', type: 'image/png', purpose: 'maskable' },
          { src: '/icons/icon-maskable-512.png',  sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
        screenshots: [],
        shortcuts: [
          { name: 'Search Songs', short_name: 'Search',  url: '/?tab=search',    icons: [{ src: '/icons/icon-96.png', sizes: '96x96' }] },
          { name: 'Liked Songs',  short_name: 'Liked',   url: '/?tab=liked',     icons: [{ src: '/icons/icon-96.png', sizes: '96x96' }] },
          { name: 'Downloads',    short_name: 'Offline', url: '/?tab=downloads', icons: [{ src: '/icons/icon-96.png', sizes: '96x96' }] },
        ],
      },
      workbox: {
        // Pre-cache all app shell assets generated by Vite
        globPatterns: ['**/*.{js,css,html,svg,png,woff2,woff}'],
        // Navigation fallback to index.html for SPA routing
        navigateFallback: 'index.html',
        navigateFallbackDenylist: [/^\/api/, /^\/saavn/],
        // Runtime caching strategies
        runtimeCaching: [
          // JioSaavn API — network-first, cache fallback
          {
            urlPattern: /\/(saavn-api|saavn-search|saavn-stream)/,
            handler: 'NetworkFirst',
            options: {
              cacheName: 'saavn-api-cache',
              networkTimeoutSeconds: 10,
              expiration: { maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          // CDN images — stale-while-revalidate
          {
            urlPattern: /^https:\/\/(.*\.saavncdn\.com|.*\.googleapis\.com|.*\.gstatic\.com)/,
            handler: 'StaleWhileRevalidate',
            options: {
              cacheName: 'image-cache',
              expiration: { maxEntries: 100, maxAgeSeconds: 60 * 60 * 24 * 7 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
          // Google Fonts
          {
            urlPattern: /^https:\/\/fonts\.(googleapis|gstatic)\.com/,
            handler: 'CacheFirst',
            options: {
              cacheName: 'google-fonts',
              expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 },
              cacheableResponse: { statuses: [0, 200] },
            },
          },
        ],
      },
      devOptions: {
        // Enable SW in dev mode so you can test the install banner locally
        enabled: false,
      },
    }),
  ],
  server: {
    port: 5173,
    open: true,
    proxy: {
      // ── Official JioSaavn API (song details + generateAuthToken) ──────────
      '/saavn-api': {
        target: 'https://www.jiosaavn.com',
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path.replace(/^\/saavn-api/, '/api.php'),
        configure: (proxy) => {
          proxy.on('proxyReq', (proxyReq) => {
            proxyReq.setHeader('Referer', 'https://www.jiosaavn.com/')
            proxyReq.setHeader('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
          })
          proxy.on('error', (err) => console.error('[saavn-api proxy]', err.message))
        },
      },

      // ── JioSaavn CDN proxy (signed stream URLs from web.saavncdn.com) ──
      '/saavn-stream': {
        target: 'https://web.saavncdn.com',
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path.replace(/^\/saavn-stream/, ''),
        configure: (proxy) => {
          proxy.on('proxyReq', (proxyReq) => {
            proxyReq.setHeader('Referer', 'https://www.jiosaavn.com/')
            proxyReq.setHeader('Origin', 'https://www.jiosaavn.com')
            proxyReq.setHeader('User-Agent', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36')
          })
          proxy.on('error', (err) => console.error('[saavn-stream proxy]', err.message))
        },
      },

      // ── Vercel JioSaavn API wrapper (for search + lyrics) ────────────────
      '/saavn-search': {
        target: 'https://jiosaavn-api-beta.vercel.app',
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path.replace(/^\/saavn-search/, ''),
        configure: (proxy) => {
          proxy.on('error', (err) => console.error('[saavn-search proxy]', err.message))
        },
      },
    },
  },
  build: {
    outDir: 'dist',
    sourcemap: false,
  },
})
