export const LANG_QUERIES = [
  { label: 'All',       term: '' },
  { label: 'Tamil',     term: 'tamil film songs' },
  { label: 'Hindi',     term: 'bollywood hindi songs' },
  { label: 'Telugu',    term: 'telugu film songs' },
  { label: 'Malayalam', term: 'malayalam film songs' },
  { label: 'Kannada',   term: 'kannada film songs' },
  { label: 'Bengali',   term: 'bengali songs' },
  { label: 'Punjabi',   term: 'punjabi songs' },
  { label: 'Marathi',   term: 'marathi film songs' },
  { label: 'Gujarati',  term: 'gujarati songs' },
  { label: 'Bhojpuri',  term: 'bhojpuri songs' },
  { label: 'Odia',      term: 'odia songs' },
  { label: 'Assamese',  term: 'assamese songs' },
  { label: 'Sanskrit',  term: 'sanskrit devotional' },
  { label: 'Urdu',      term: 'urdu ghazal' },
  { label: 'Rajasthani', term: 'rajasthani folk' },
];

export const HOME_SECTIONS = [
  { key: 'trending',    label: 'Trending India',           query: 'trending india 2025' },
  { key: 'hindi',       label: 'Bollywood Hits',           query: 'bollywood hindi songs' },
  { key: 'tamil',       label: 'Tamil Hits',               query: 'tamil film songs' },
  { key: 'telugu',      label: 'Telugu Hits',              query: 'telugu film songs' },
  { key: 'malayalam',   label: 'Malayalam Hits',           query: 'malayalam film songs' },
  { key: 'punjabi',     label: 'Punjabi Hits',             query: 'punjabi songs' },
  { key: 'kannada',     label: 'Kannada Hits',             query: 'kannada film songs' },
  { key: 'bengali',     label: 'Bengali Hits',             query: 'bengali songs' },
  { key: 'marathi',     label: 'Marathi Hits',             query: 'marathi film songs' },
  { key: 'bhojpuri',    label: 'Bhojpuri Hits',            query: 'bhojpuri songs' },
  { key: 'hindiold',    label: 'Old Hindi Classics',       query: 'old hindi songs' },
  { key: 'tamilold',    label: 'Tamil Old Classics',       query: 'Ilaiyaraaja old tamil songs' },
  { key: 'kannadaold',  label: 'Kannada Classics',         query: 'kannada old songs' },
  { key: 'romantic',    label: 'Romantic Hits',            query: 'romantic songs' },
  { key: 'mayavi',      label: 'Mayavi (Lifeu Ishtene)',    query: 'Lifeu Ishtene kannada songs' },
  { key: 'mgr',         label: 'MGR Hits',                 query: 'Annakili songs' },
  { key: 'sivaji',      label: 'Sivaji Ganesan Classics',  query: 'Thiruvilaiyadal songs' },
  { key: 'msv',         label: 'M.S. Viswanathan',         query: 'M.S. Viswanathan Tamil' },
  { key: 'arrijit',     label: 'Arijit Singh',             query: 'Arijit Singh songs' },
  { key: 'arrahman',    label: 'A.R. Rahman',              query: 'A.R. Rahman songs' },
  { key: 'anirudh',     label: 'Anirudh Ravichander',      query: 'Anirudh songs' },
  { key: 'shreya',      label: 'Shreya Ghoshal',           query: 'Shreya Ghoshal songs' },
  { key: 'ilayaraja',   label: 'Ilaiyaraaja',              query: 'Ilaiyaraaja songs' },
  { key: 'yesudas',     label: 'K.J. Yesudas',             query: 'K.J. Yesudas Tamil songs' },
  { key: 'spb',         label: 'S.P. Balasubrahmanyam',    query: 'S.P. Balasubrahmanyam songs' },
  { key: 'lata',        label: 'Lata Mangeshkar',          query: 'Lata Mangeshkar songs' },
  { key: 'kishore',     label: 'Kishore Kumar',            query: 'Kishore Kumar songs' },
  { key: 'sonu',        label: 'Sonu Nigam',               query: 'Sonu Nigam songs' },
  { key: 'udit',        label: 'Udit Narayan',             query: 'Udit Narayan songs' },
  { key: 'sanjith',     label: 'Sanjith Hegde',            query: 'Sanjith Hegde songs' },
  { key: 'sonu_kan',    label: 'Sonu Nigam Kannada',       query: 'Sonu Nigam kannada songs' },
];
