export const LANG_QUERIES = [
  { label: 'All',       term: '' },
  { label: 'Tamil',     term: 'tamil film songs' },
  { label: 'Hindi',     term: 'bollywood hindi' },
  { label: 'Telugu',    term: 'telugu film' },
  { label: 'Malayalam', term: 'malayalam film' },
  { label: 'Kannada',   term: 'kannada film' },
  { label: 'Bengali',   term: 'bengali' },
  { label: 'Punjabi',   term: 'punjabi' },
  { label: 'Marathi',   term: 'marathi' },
  { label: 'Gujarati',  term: 'gujarati' },
  { label: 'Bhojpuri',  term: 'bhojpuri' },
  { label: 'Odia',      term: 'odia' },
  { label: 'Assamese',  term: 'assamese' },
  { label: 'Sanskrit',  term: 'sanskrit devotional' },
  { label: 'Urdu',      term: 'urdu ghazal' },
  { label: 'Rajasthani', term: 'rajasthani folk' },
];

export const HOME_SECTIONS = [
  { key: 'trending',    label: 'Trending India',          query: 'trending india 2025' },
  { key: 'hindi',       label: 'Bollywood Hits',          query: 'bollywood hindi 2025' },
  { key: 'tamil',       label: 'Tamil Hits',              query: 'tamil film songs' },
  { key: 'telugu',      label: 'Telugu Hits',             query: 'telugu film songs' },
  { key: 'malayalam',   label: 'Malayalam Hits',          query: 'malayalam film songs' },
  { key: 'punjabi',     label: 'Punjabi Hits',            query: 'punjabi songs' },
  { key: 'kannada',     label: 'Kannada Hits',            query: 'kannada film songs' },
  { key: 'bengali',     label: 'Bengali Hits',            query: 'bengali film songs' },
  { key: 'marathi',     label: 'Marathi Hits',            query: 'marathi film songs' },
  { key: 'bhojpuri',    label: 'Bhojpuri Hits',           query: 'bhojpuri songs' },
  { key: 'romantic',    label: 'Romantic Hits',           query: 'romantic bollywood' },
  { key: 'arrijit',     label: 'Arijit Singh',            query: 'Arijit Singh' },
  { key: 'arrahman',    label: 'A.R. Rahman',             query: 'A.R. Rahman' },
  { key: 'anirudh',     label: 'Anirudh Ravichander',     query: 'Anirudh Ravichander' },
  { key: 'shreya',      label: 'Shreya Ghoshal',          query: 'Shreya Ghoshal' },
  { key: 'ilayaraja',   label: 'Ilaiyaraaja',             query: 'Ilaiyaraaja' },
  { key: 'yesudas',     label: 'K.J. Yesudas',            query: 'K.J. Yesudas' },
  { key: 'msv',         label: 'M.S. Viswanathan',        query: 'M.S. Viswanathan' },
  { key: 'kannadasan',  label: 'Kannadasan',              query: 'Kannadasan songs' },
  { key: 'spb',         label: 'S.P. Balasubrahmanyam',   query: 'S.P. Balasubrahmanyam' },
  { key: 'lata',        label: 'Lata Mangeshkar',         query: 'Lata Mangeshkar' },
  { key: 'kishore',     label: 'Kishore Kumar',           query: 'Kishore Kumar' },
  { key: 'mukesh',      label: 'Mukesh',                  query: 'Mukesh singer' },
  { key: 'sonu',        label: 'Sonu Nigam',              query: 'Sonu Nigam' },
  { key: 'udit',        label: 'Udit Narayan',            query: 'Udit Narayan' },
  { key: 'alka',        label: 'Alka Yagnik',             query: 'Alka Yagnik' },
  { key: 'pritham',     label: 'Pritam',                  query: 'Pritam music' },
  { key: 'vishal',      label: 'Vishal-Shekhar',          query: 'Vishal Shekhar' },
  { key: 'shankar',     label: 'Shankar-Ehsaan-Loy',      query: 'Shankar Ehsaan Loy' },
  { key: 'sadha',       label: 'Old Hindi Classics',      query: 'old hindi songs golden era' },
  { key: 'tamilold',    label: 'Tamil Old Hits',          query: 'tamil old song hits' },
];
