export const LANG_QUERIES = [
  { label: 'All',        term: '' },
  { label: 'Tamil',      term: 'tamil film songs' },
  { label: 'Hindi',      term: 'bollywood hindi songs' },
  { label: 'Telugu',     term: 'telugu film songs' },
  { label: 'Malayalam',  term: 'malayalam film songs' },
  { label: 'Kannada',    term: 'kannada film songs' },
  { label: 'Bengali',    term: 'bengali songs' },
  { label: 'Punjabi',    term: 'punjabi songs' },
  { label: 'Marathi',    term: 'marathi film songs' },
  { label: 'Gujarati',   term: 'gujarati songs' },
  { label: 'Bhojpuri',   term: 'bhojpuri songs' },
  { label: 'Odia',       term: 'odia songs' },
  { label: 'Assamese',   term: 'assamese songs' },
  { label: 'Sanskrit',   term: 'sanskrit devotional' },
  { label: 'Urdu',       term: 'urdu ghazal' },
  { label: 'Rajasthani', term: 'rajasthani folk' },
];

export const HOME_SECTIONS = [
  // ── Trending & Popular ──
  { key: 'trending',      label: 'Trending India',             query: 'trending india 2025' },
  { key: 'romantic',      label: 'Romantic Hits',              query: 'romantic songs' },
  { key: 'dance',         label: 'Party & Dance Hits',         query: 'bollywood dance hits' },
  { key: 'sad',           label: 'Sad Songs',                  query: 'hindi sad songs' },
  { key: 'indiepop',      label: 'Indian Pop (I-Pop)',         query: 'indian pop songs 2025' },
  { key: 'indie2025',     label: 'New Releases 2025',         query: 'new bollywood songs 2025' },
  { key: 'topAlbums',     label: 'Top Albums 2025',           query: 'bollywood albums 2025' },
  { key: 'topPunjabi',    label: 'Top Punjabi 2025',          query: 'punjabi hits 2025' },
  { key: 'topIndie',      label: 'Indian Indie',              query: 'indian independent music' },

  // ── Language Hits ──
  { key: 'hindi',         label: 'Bollywood Hits',             query: 'bollywood hindi songs' },
  { key: 'tamil',         label: 'Tamil Hits',                 query: 'tamil film songs' },
  { key: 'telugu',        label: 'Telugu Hits',                query: 'telugu film songs' },
  { key: 'malayalam',     label: 'Malayalam Hits',             query: 'malayalam film songs' },
  { key: 'kannada',       label: 'Kannada Hits',               query: 'kannada film songs' },
  { key: 'bengali',       label: 'Bengali Hits',               query: 'bengali songs' },
  { key: 'punjabi',       label: 'Punjabi Hits',               query: 'punjabi songs' },
  { key: 'marathi',       label: 'Marathi Hits',               query: 'marathi film songs' },
  { key: 'bhojpuri',      label: 'Bhojpuri Hits',              query: 'bhojpuri songs' },
  { key: 'gujarati',      label: 'Gujarati Hits',              query: 'gujarati songs' },

  // ── Old Classics ──
  { key: 'hindiold',      label: 'Old Hindi Classics',         query: 'old hindi songs golden era' },
  { key: 'tamilold',      label: 'Tamil Old Classics',         query: 'Ilaiyaraaja old tamil songs' },
  { key: 'kannadaold',    label: 'Kannada Classics',           query: 'kannada old songs' },
  { key: 'malayalamold',  label: 'Malayalam Classics',         query: 'm s viswanathan malayalam' },
  { key: 'teluguold',     label: 'Telugu Classics',            query: 'telugu old songs' },
  { key: 'punjabiold',    label: 'Punjabi Classics',           query: 'old punjabi songs' },

  // ── Tamil Albums & Themes ──
  { key: 'mayavi',        label: 'Mayavi (Lifeu Ishtene)',     query: 'Lifeu Ishtene kannada songs' },
  { key: 'mgr',           label: 'MGR Hits',                   query: 'Annakili songs' },
  { key: 'sivaji',        label: 'Sivaji Ganesan Classics',    query: 'Thiruvilaiyadal songs' },
  { key: 'msv',           label: 'M.S. Viswanathan',           query: 'M.S. Viswanathan Tamil' },
  { key: 'tamildevotional', label: 'Tamil Devotional',         query: 'tamil devotional songs' },
  { key: 'tamilindie',    label: 'Tamil Album Songs',          query: 'tamil album songs' },
  { key: 'rajinikanth',   label: 'Rajinikanth Hits',           query: 'rajinikanth songs' },
  { key: 'kamal',         label: 'Kamal Haasan Hits',          query: 'kamal haasan songs' },
  { key: 'vijay',         label: 'Vijay Hits',                 query: 'vijay actor songs' },
  { key: 'ajith',         label: 'Ajith Hits',                 query: 'ajith kumar songs' },

  // ── Kannada Albums & Themes ──
  { key: 'kannadaindie',  label: 'Kannada Album Songs',        query: 'kannada album songs' },
  { key: 'puneeth',       label: 'Puneeth Rajkumar Hits',      query: 'puneeth rajkumar songs' },
  { key: 'darshan',       label: 'Darshan Hits',               query: 'darshan kannada songs' },
  { key: 'upendra',       label: 'Upendra Hits',               query: 'upendra kannada songs' },
  { key: 'drrajkumar',    label: 'Dr. Rajkumar Classics',      query: 'dr rajkumar songs kannada' },
  { key: 'kannadadevo',   label: 'Kannada Devotional',         query: 'kannada devotional songs' },

  // ── Hindi / Bollywood Specific ──
  { key: 'shahrukh',      label: 'Shah Rukh Khan Hits',        query: 'shah rukh khan songs' },
  { key: 'salman',        label: 'Salman Khan Hits',           query: 'salman khan songs' },
  { key: 'amir',          label: 'Aamir Khan Hits',            query: 'aamir khan songs' },
  { key: 'ranbir',        label: 'Ranbir Kapoor Hits',         query: 'ranbir kapoor songs' },

  // ── Composer-Specific ──
  { key: 'arrijit',       label: 'Arijit Singh',               query: 'Arijit Singh songs' },
  { key: 'pritam',        label: 'Pritam',                     query: 'Pritam songs' },
  { key: 'arrahman',      label: 'A.R. Rahman',                query: 'A.R. Rahman songs' },
  { key: 'anirudh',       label: 'Anirudh Ravichander',        query: 'Anirudh songs' },
  { key: 'shreya',        label: 'Shreya Ghoshal',             query: 'Shreya Ghoshal songs' },
  { key: 'sachinjigar',   label: 'Sachin-Jigar',               query: 'Sachin-Jigar songs' },
  { key: 'tanishk',       label: 'Tanishk Bagchi',             query: 'Tanishk Bagchi songs' },
  { key: 'ilayaraja',     label: 'Ilaiyaraaja',                query: 'Ilaiyaraaja songs' },
  { key: 'dsp',           label: 'Devi Sri Prasad',            query: 'Devi Sri Prasad songs' },
  { key: 'yuvan',         label: 'Yuvan Shankar Raja',         query: 'Yuvan Shankar Raja songs' },
  { key: 'harris',        label: 'Harris Jayaraj',             query: 'Harris Jayaraj songs' },
  { key: 'ss_thaman',     label: 'S.S. Thaman',                query: 'S.S. Thaman songs' },
  { key: 'harish',        label: 'Haricharan',                 query: 'Haricharan songs' },
  { key: 'sid',           label: 'Sid Sriram',                 query: 'Sid Sriram songs' },
  { key: 'vishalM',       label: 'Vishal Mishra',              query: 'Vishal Mishra songs' },
  { key: 'himesh',        label: 'Himesh Reshammiya',          query: 'Himesh Reshammiya songs' },
  { key: 'jubin',         label: 'Jubin Nautiyal',             query: 'Jubin Nautiyal songs' },
  { key: 'neha',          label: 'Neha Kakkar',                query: 'Neha Kakkar songs' },
  { key: 'sachet',        label: 'Sachet-Parampara',           query: 'Sachet Parampara songs' },
  { key: 'anuv',          label: 'Anuv Jain',                  query: 'Anuv Jain songs' },
  { key: 'kushagra',      label: 'Kushagra',                   query: 'Kushagra songs' },
  { key: 'faheem',        label: 'Faheem Abdullah',            query: 'Faheem Abdullah songs' },
  { key: 'aditya',        label: 'Aditya Rikhari',             query: 'Aditya Rikhari songs' },
  { key: 'hanumankind',   label: 'Hanumankind',                query: 'Hanumankind songs' },
  { key: 'vishal',        label: 'Vishal-Shekhar',             query: 'Vishal Shekhar songs' },
  { key: 'salim',         label: 'Salim-Sulaiman',             query: 'Salim Sulaiman songs' },
  { key: 'emiway',        label: 'Emiway Bantai',              query: 'Emiway Bantai songs' },

  // ── Legendary Singers ──
  { key: 'yesudas',       label: 'K.J. Yesudas',               query: 'K.J. Yesudas songs' },
  { key: 'spb',           label: 'S.P. Balasubrahmanyam',      query: 'S.P. Balasubrahmanyam songs' },
  { key: 'lata',          label: 'Lata Mangeshkar',            query: 'Lata Mangeshkar songs' },
  { key: 'kishore',       label: 'Kishore Kumar',              query: 'Kishore Kumar songs' },
  { key: 'mukesh',        label: 'Mukesh',                     query: 'Mukesh songs' },
  { key: 'rafi',          label: 'Mohammed Rafi',              query: 'Mohammed Rafi songs' },
  { key: 'asha',          label: 'Asha Bhosle',                query: 'Asha Bhosle songs' },
  { key: 'sonu',          label: 'Sonu Nigam',                 query: 'Sonu Nigam songs' },
  { key: 'udit',          label: 'Udit Narayan',               query: 'Udit Narayan songs' },
  { key: 'alka',          label: 'Alka Yagnik',                query: 'Alka Yagnik songs' },
  { key: 'kumarSanu',     label: 'Kumar Sanu',                 query: 'Kumar Sanu songs' },
  { key: 'sunidhi',       label: 'Sunidhi Chauhan',            query: 'Sunidhi Chauhan songs' },
  { key: 'shankar',       label: 'Shankar Mahadevan',          query: 'Shankar Mahadevan songs' },
  { key: 'kannadasan',    label: 'Kannadasan',                 query: 'Kannadasan songs' },
  { key: 'msv2',          label: 'M.S. Viswanathan',           query: 'M.S. Viswanathan songs' },

  // ── Punjabi & Hip-Hop ──
  { key: 'diljit',        label: 'Diljit Dosanjh',             query: 'Diljit Dosanjh songs' },
  { key: 'badshah',       label: 'Badshah',                    query: 'Badshah songs' },
  { key: 'honey',         label: 'Honey Singh',                query: 'Honey Singh songs' },
  { key: 'guru',          label: 'Guru Randhawa',              query: 'Guru Randhawa songs' },
  { key: 'karun',         label: 'Karun Aujla',                query: 'Karun Aujla songs' },
  { key: 'ap',            label: 'AP Dhillon',                 query: 'AP Dhillon songs' },

  // ── Malayalam Specific ──
  { key: 'mammootty',     label: 'Mammootty Hits',             query: 'mammootty songs' },
  { key: 'mohanlal',      label: 'Mohanlal Hits',              query: 'mohanlal songs' },
  { key: 'prithviraj',    label: 'Prithviraj Hits',            query: 'prithviraj songs' },

  // ── Telugu Specific ──
  { key: 'mahesh',        label: 'Mahesh Babu Hits',           query: 'mahesh babu songs' },
  { key: 'prabhas',       label: 'Prabhas Hits',               query: 'prabhas songs' },
  { key: 'allu',          label: 'Allu Arjun Hits',            query: 'allu arjun songs' },
  { key: 'ram',           label: 'Ram Charan Hits',            query: 'ram charan songs' },
  { key: 'ntr',           label: 'Jr NTR Hits',                query: 'junior ntr songs' },

  // ── Bengali ──
  { key: 'riba',          label: 'Rituparna Sengupta',         query: 'bengali film songs' },
  { key: 'jeet',          label: 'Jeet Gannguli',              query: 'jeet gannguli songs' },

  // ── Devotional ──
  { key: 'ganesh',        label: 'Ganesh Chalisa & Aarti',     query: 'ganesh aarti' },
  { key: 'krishna',       label: 'Krishna Bhajans',            query: 'krishna bhajans' },
  { key: 'shiva',         label: 'Shiva Bhajans',              query: 'shiv bhajans' },
  { key: 'durga',         label: 'Durga Maa Bhajans',          query: 'durga maa bhajans' },
  { key: 'tulsi',         label: 'Tulsi Vivah Songs',          query: 'tulsi vivah songs' },
];

export const INDIAN_ARTISTS = [
  // ── Hindi / Bollywood ──
  { name: 'Arijit Singh',           lang: 'Hindi' },
  { name: 'A.R. Rahman',            lang: 'Multi' },
  { name: 'Shreya Ghoshal',         lang: 'Multi' },
  { name: 'Sonu Nigam',             lang: 'Multi' },
  { name: 'Udit Narayan',           lang: 'Hindi' },
  { name: 'Lata Mangeshkar',        lang: 'Hindi' },
  { name: 'Kishore Kumar',          lang: 'Hindi' },
  { name: 'Mukesh',                 lang: 'Hindi' },
  { name: 'Mohammed Rafi',          lang: 'Hindi' },
  { name: 'Asha Bhosle',            lang: 'Hindi' },
  { name: 'Sunidhi Chauhan',        lang: 'Hindi' },
  { name: 'Shankar Mahadevan',      lang: 'Hindi' },
  { name: 'Vishal-Shekhar',         lang: 'Hindi' },
  { name: 'Salim-Sulaiman',         lang: 'Hindi' },
  { name: 'Badshah',                lang: 'Hindi' },
  { name: 'Honey Singh',            lang: 'Hindi' },
  { name: 'Atif Aslam',             lang: 'Hindi' },
  { name: 'KK',                     lang: 'Hindi' },
  { name: 'Amit Trivedi',           lang: 'Hindi' },
  { name: 'Pritam',                 lang: 'Hindi' },
  { name: 'Sachin-Jigar',           lang: 'Hindi' },
  { name: 'Tanishk Bagchi',         lang: 'Hindi' },
  { name: 'Himesh Reshammiya',      lang: 'Hindi' },
  { name: 'Alka Yagnik',            lang: 'Hindi' },
  { name: 'Kumar Sanu',             lang: 'Hindi' },
  { name: 'Anuv Jain',              lang: 'Hindi' },
  { name: 'Kushagra',               lang: 'Hindi' },
  { name: 'Faheem Abdullah',        lang: 'Hindi' },
  { name: 'Aditya Rikhari',         lang: 'Hindi' },
  { name: 'Hanumankind',            lang: 'Hindi' },
  { name: 'Jubin Nautiyal',         lang: 'Hindi' },
  { name: 'Neha Kakkar',            lang: 'Hindi' },
  { name: 'Vishal Mishra',          lang: 'Hindi' },
  { name: 'Sachet-Parampara',       lang: 'Hindi' },
  { name: 'Karan Aujla',            lang: 'Punjabi' },

  // ── Tamil ──
  { name: 'Anirudh Ravichander',    lang: 'Tamil' },
  { name: 'Ilaiyaraaja',            lang: 'Tamil' },
  { name: 'Yuvan Shankar Raja',     lang: 'Tamil' },
  { name: 'Harris Jayaraj',         lang: 'Tamil' },
  { name: 'S.P. Balasubrahmanyam',  lang: 'Multi' },
  { name: 'K.J. Yesudas',           lang: 'Multi' },
  { name: 'Kannadasan',             lang: 'Tamil' },
  { name: 'M.S. Viswanathan',       lang: 'Tamil' },
  { name: 'Sid Sriram',             lang: 'Multi' },
  { name: 'Haricharan',             lang: 'Multi' },
  { name: 'Chinmayi',               lang: 'Multi' },
  { name: 'D. Imman',               lang: 'Tamil' },
  { name: 'G.V. Prakash Kumar',     lang: 'Tamil' },
  { name: 'Santhosh Narayanan',     lang: 'Tamil' },
  { name: 'Thaman S',               lang: 'Multi' },
  { name: 'Tippu',                  lang: 'Tamil' },
  { name: 'Unni Menon',             lang: 'Tamil' },
  { name: 'S.P.B. Charan',          lang: 'Tamil' },

  // ── Kannada ──
  { name: 'Sonu Nigam Kannada',     lang: 'Kannada' },
  { name: 'Sanjith Hegde',          lang: 'Kannada' },
  { name: 'Rajesh Krishnan',        lang: 'Kannada' },
  { name: 'Raghu Dixit',            lang: 'Kannada' },
  { name: 'Chandan Shetty',         lang: 'Kannada' },
  { name: 'V. Harikrishna',         lang: 'Kannada' },
  { name: 'Hamsalekha',             lang: 'Kannada' },
  { name: 'Guru Kiran',             lang: 'Kannada' },
  { name: 'Arjun Janya',            lang: 'Kannada' },
  { name: 'Anuradha Bhat',          lang: 'Kannada' },

  // ── Telugu ──
  { name: 'Devi Sri Prasad',        lang: 'Telugu' },
  { name: 'S.S. Thaman',            lang: 'Telugu' },
  { name: 'Keeravani',              lang: 'Telugu' },
  { name: 'MM Keeravani',           lang: 'Telugu' },
  { name: 'DSP',                    lang: 'Telugu' },
  { name: 'Thaman S',               lang: 'Telugu' },
  { name: 'Sid Sriram Telugu',      lang: 'Telugu' },
  { name: 'Shreya Ghoshal Telugu',  lang: 'Telugu' },

  // ── Malayalam ──
  { name: 'Vidyadharan Master',     lang: 'Malayalam' },
  { name: 'Shreya Ghoshal Malayalam', lang: 'Malayalam' },
  { name: 'Vineeth Sreenivasan',    lang: 'Malayalam' },
  { name: 'K.J. Yesudas Malayalam', lang: 'Malayalam' },

  // ── Punjabi ──
  { name: 'Diljit Dosanjh',         lang: 'Punjabi' },
  { name: 'Guru Randhawa',          lang: 'Punjabi' },
  { name: 'Karun Aujla',            lang: 'Punjabi' },
  { name: 'AP Dhillon',             lang: 'Punjabi' },
  { name: 'Amrinder Gill',          lang: 'Punjabi' },
  { name: 'Gurdas Maan',            lang: 'Punjabi' },
  { name: 'Jass Manak',             lang: 'Punjabi' },
  { name: 'Karan Aujla',            lang: 'Punjabi' },

  // ── Marathi ──
  { name: 'Ajay-Atul',              lang: 'Marathi' },
  { name: 'Avadhoot Gupte',         lang: 'Marathi' },

  // ── Bengali ──
  { name: 'Jeet Gannguli',          lang: 'Bengali' },
  { name: 'Anupam Roy',             lang: 'Bengali' },
];
